// Code generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.
// Surface `delta` from schemas/delta.json, model sha256:cf7dfa4e63bdb67441babc61f7e861b18cb1a9d822ca8e6b8757d66ce943b5e7.
// Regenerate from lazily-spec with `make wire-codegen`; semantics stay hand-written.

package lazily

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"sort"
	"strconv"
)

// deltaWireField is one key of a JSON object, written in declaration order.
type deltaWireField struct {
	name  string
	value any
}

// deltaWireObject writes a JSON object whose keys keep declaration order.
func deltaWireObject(fields []deltaWireField) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteByte('{')
	for i, f := range fields {
		if i > 0 {
			buf.WriteByte(',')
		}
		key, err := json.Marshal(f.name)
		if err != nil {
			return nil, err
		}
		value, err := json.Marshal(f.value)
		if err != nil {
			return nil, err
		}
		buf.Write(key)
		buf.WriteByte(':')
		buf.Write(value)
	}
	buf.WriteByte('}')
	return buf.Bytes(), nil
}

// deltaWireTagged wraps an encoded body as the externally-tagged {tag: body}.
func deltaWireTagged(tag string, body any) ([]byte, error) {
	return deltaWireObject([]deltaWireField{{tag, body}})
}

// deltaWireFields decodes a JSON object whose keys are every required field and
// any optional ones, rejecting an unknown or missing key.
func deltaWireFields(name string, data []byte, required, optional []string) (map[string]json.RawMessage, error) {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 || trimmed[0] != '{' {
		return nil, fmt.Errorf("%s: expected an object, got %s", name, trimmed)
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(trimmed, &fields); err != nil {
		return nil, fmt.Errorf("%s: %w", name, err)
	}
	for _, key := range required {
		if _, ok := fields[key]; !ok {
			return nil, fmt.Errorf("%s: missing field %q", name, key)
		}
	}
	unknown := make([]string, 0)
	for key := range fields {
		if !deltaWireContains(required, key) && !deltaWireContains(optional, key) {
			unknown = append(unknown, key)
		}
	}
	if len(unknown) > 0 {
		sort.Strings(unknown)
		return nil, fmt.Errorf("%s: unknown field %q", name, unknown[0])
	}
	return fields, nil
}

func deltaWireContains(keys []string, key string) bool {
	for _, k := range keys {
		if k == key {
			return true
		}
	}
	return false
}

// deltaWireIsNull reports whether raw is the JSON null literal.
func deltaWireIsNull(raw json.RawMessage) bool {
	return bytes.Equal(bytes.TrimSpace(raw), []byte("null"))
}

// deltaWireTag splits an externally-tagged single-key object.
func deltaWireTag(name string, raw json.RawMessage) (string, json.RawMessage, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || trimmed[0] != '{' {
		return "", nil, fmt.Errorf("%s: expected a single-key object, got %s", name, trimmed)
	}
	var tagged map[string]json.RawMessage
	if err := json.Unmarshal(trimmed, &tagged); err != nil {
		return "", nil, fmt.Errorf("%s: %w", name, err)
	}
	if len(tagged) != 1 {
		return "", nil, fmt.Errorf("%s: expected a single-key object, got %d keys", name, len(tagged))
	}
	for tag, body := range tagged {
		return tag, body, nil
	}
	return "", nil, fmt.Errorf("%s: expected a single-key object", name)
}

func deltaWireString(name string, raw json.RawMessage) (string, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || trimmed[0] != '"' {
		return "", fmt.Errorf("%s: expected a string, got %s", name, trimmed)
	}
	var s string
	if err := json.Unmarshal(trimmed, &s); err != nil {
		return "", fmt.Errorf("%s: %w", name, err)
	}
	return s, nil
}

// deltaWireU64 decodes an unsigned integer literal: digits only, no sign, fraction,
// exponent or leading zero, and at most 2^64-1.
func deltaWireU64(name string, raw json.RawMessage) (uint64, error) {
	trimmed := string(bytes.TrimSpace(raw))
	valid := trimmed != "" && (trimmed == "0" || trimmed[0] != '0')
	for _, c := range trimmed {
		if c < '0' || c > '9' {
			valid = false
		}
	}
	if !valid {
		return 0, fmt.Errorf("%s: expected an unsigned integer, got %s", name, trimmed)
	}
	v, err := strconv.ParseUint(trimmed, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("%s: expected an unsigned integer in 0..=2^64-1, got %s", name, trimmed)
	}
	return v, nil
}

// deltaWireInt64 decodes a u64 into a signed 64-bit field. A value past
// 2^63-1 is refused rather than wrapped: a binding that cannot represent a
// wire value exactly must reject the frame (protocol.md § NodeId / PeerId).
func deltaWireInt64(name string, raw json.RawMessage) (int64, error) {
	v, err := deltaWireU64(name, raw)
	if err != nil {
		return 0, err
	}
	if v > math.MaxInt64 {
		return 0, fmt.Errorf("%s: %d exceeds this binding's int64 range", name, v)
	}
	return int64(v), nil
}

// deltaWireCheckInt64 refuses to encode a negative value as a u64.
func deltaWireCheckInt64(name string, v int64) error {
	if v < 0 {
		return fmt.Errorf("%s: %d is negative; the wire type is u64", name, v)
	}
	return nil
}

// deltaWireBytes decodes serialized bytes from a JSON array of u8 (never base64).
func deltaWireBytes(name string, raw json.RawMessage) ([]byte, error) {
	items, err := deltaWireList(name, raw)
	if err != nil {
		return nil, err
	}
	out := make([]byte, len(items))
	for i, item := range items {
		v, err := deltaWireU64(name, item)
		if err != nil || v > 255 {
			return nil, fmt.Errorf("%s: expected an array of bytes (0..=255), got %s", name, bytes.TrimSpace(raw))
		}
		out[i] = byte(v)
	}
	return out, nil
}

// deltaWireByteArray encodes bytes as a JSON array of u8; empty is [].
func deltaWireByteArray(b []byte) []int {
	out := make([]int, len(b))
	for i, x := range b {
		out[i] = int(x)
	}
	return out
}

func deltaWireList(name string, raw json.RawMessage) ([]json.RawMessage, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || trimmed[0] != '[' {
		return nil, fmt.Errorf("%s: expected an array, got %s", name, trimmed)
	}
	var items []json.RawMessage
	if err := json.Unmarshal(trimmed, &items); err != nil {
		return nil, fmt.Errorf("%s: %w", name, err)
	}
	return items, nil
}

// DeltaOp: One incremental graph mutation. Externally tagged: a single-key
// object whose key is the PascalCase variant name.
type DeltaOp interface {
	json.Marshaler
	// TargetReadable reports whether peer may read every node this op names. Ops
	// targeting an unreadable node are omitted from a permission-filtered delta.
	TargetReadable(permissions *PeerPermissions, peer PeerId) bool
	isDeltaOp()
}

// unmarshalDeltaOp decodes a DeltaOp strictly: exactly one known variant.
func unmarshalDeltaOp(raw json.RawMessage) (DeltaOp, error) {
	tag, inner, err := deltaWireTag("DeltaOp", raw)
	if err != nil {
		return nil, err
	}
	switch tag {
	case "CellSet":
		return unmarshalDeltaOpCellSet(inner)
	case "SlotValue":
		return unmarshalDeltaOpSlotValue(inner)
	case "Invalidate":
		return unmarshalDeltaOpInvalidate(inner)
	case "NodeAdd":
		return unmarshalDeltaOpNodeAdd(inner)
	case "NodeRemove":
		return unmarshalDeltaOpNodeRemove(inner)
	case "EdgeAdd":
		return unmarshalDeltaOpEdgeAdd(inner)
	case "EdgeRemove":
		return unmarshalDeltaOpEdgeRemove(inner)
	case "QueuePush":
		return unmarshalDeltaOpQueuePush(inner)
	case "QueuePop":
		return unmarshalDeltaOpQueuePop(inner)
	case "QueueClose":
		return unmarshalDeltaOpQueueClose(inner)
	}
	return nil, fmt.Errorf("unknown DeltaOp variant: %s", tag)
}

// DeltaOpCellSet: A source cell was changed to `payload`.
type DeltaOpCellSet struct {
	// Node: Target node.
	Node NodeId
	// Payload: Value, inline or by blob descriptor.
	Payload IpcValue
}

func (DeltaOpCellSet) isDeltaOp() {}

// MarshalJSON emits {"CellSet": {...}}, omitting an absent optional field.
func (o DeltaOpCellSet) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.CellSet.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
		{"payload", o.Payload},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("CellSet", json.RawMessage(inner))
}

func unmarshalDeltaOpCellSet(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.CellSet", data, []string{"node", "payload"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.CellSet.node", f["node"])
	if err != nil {
		return nil, err
	}
	fPayload, err := unmarshalIpcValue(f["payload"])
	if err != nil {
		return nil, err
	}
	return DeltaOpCellSet{Node: fNode, Payload: fPayload}, nil
}

// DeltaOpSlotValue: A lazily recomputed slot published a concrete value.
type DeltaOpSlotValue struct {
	// Node: Target node.
	Node NodeId
	// Payload: Value, inline or by blob descriptor.
	Payload IpcValue
}

func (DeltaOpSlotValue) isDeltaOp() {}

// MarshalJSON emits {"SlotValue": {...}}, omitting an absent optional field.
func (o DeltaOpSlotValue) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.SlotValue.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
		{"payload", o.Payload},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("SlotValue", json.RawMessage(inner))
}

func unmarshalDeltaOpSlotValue(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.SlotValue", data, []string{"node", "payload"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.SlotValue.node", f["node"])
	if err != nil {
		return nil, err
	}
	fPayload, err := unmarshalIpcValue(f["payload"])
	if err != nil {
		return nil, err
	}
	return DeltaOpSlotValue{Node: fNode, Payload: fPayload}, nil
}

// DeltaOpInvalidate: A node was dirtied without publishing a concrete value.
type DeltaOpInvalidate struct {
	// Node: Target node.
	Node NodeId
}

func (DeltaOpInvalidate) isDeltaOp() {}

// MarshalJSON emits {"Invalidate": {...}}, omitting an absent optional field.
func (o DeltaOpInvalidate) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.Invalidate.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("Invalidate", json.RawMessage(inner))
}

func unmarshalDeltaOpInvalidate(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.Invalidate", data, []string{"node"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.Invalidate.node", f["node"])
	if err != nil {
		return nil, err
	}
	return DeltaOpInvalidate{Node: fNode}, nil
}

// DeltaOpNodeAdd: A new node became visible.
type DeltaOpNodeAdd struct {
	// Node: New node.
	Node NodeId
	// TypeTag: Binding-defined type tag of the new node.
	TypeTag string
	// State: Initial node body.
	State NodeState
	// Key: Optional wire-stable keyed address. A conforming ENCODER omits it when
	// absent; an explicit null is also wire-valid and a decoder MUST read both
	// forms as absent (protocol.md § NodeKey, #lzkeynullstrict). This carried a
	// bare NodeKey $ref until that audit, which made a frame the spec now requires
	// decoders to accept schema-invalid.
	Key *NodeKey
}

func (DeltaOpNodeAdd) isDeltaOp() {}

// MarshalJSON emits {"NodeAdd": {...}}, omitting an absent optional field.
func (o DeltaOpNodeAdd) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.NodeAdd.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
		{"type_tag", o.TypeTag},
		{"state", o.State},
	}
	if o.Key != nil {
		fields = append(fields, deltaWireField{"key", o.Key})
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("NodeAdd", json.RawMessage(inner))
}

func unmarshalDeltaOpNodeAdd(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.NodeAdd", data, []string{"node", "type_tag", "state"}, []string{"key"})
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.NodeAdd.node", f["node"])
	if err != nil {
		return nil, err
	}
	fTypeTag, err := deltaWireString("DeltaOp.NodeAdd.type_tag", f["type_tag"])
	if err != nil {
		return nil, err
	}
	fState, err := unmarshalNodeState(f["state"])
	if err != nil {
		return nil, err
	}
	var fKey *NodeKey
	if raw, ok := f["key"]; ok && !deltaWireIsNull(raw) {
		var v NodeKey
		if err := json.Unmarshal(raw, &v); err != nil {
			return nil, fmt.Errorf("DeltaOp.NodeAdd.key: %w", err)
		}
		fKey = &v
	}
	return DeltaOpNodeAdd{Node: fNode, TypeTag: fTypeTag, State: fState, Key: fKey}, nil
}

// DeltaOpNodeRemove: A node was removed.
type DeltaOpNodeRemove struct {
	// Node: Target node.
	Node NodeId
}

func (DeltaOpNodeRemove) isDeltaOp() {}

// MarshalJSON emits {"NodeRemove": {...}}, omitting an absent optional field.
func (o DeltaOpNodeRemove) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.NodeRemove.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("NodeRemove", json.RawMessage(inner))
}

func unmarshalDeltaOpNodeRemove(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.NodeRemove", data, []string{"node"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.NodeRemove.node", f["node"])
	if err != nil {
		return nil, err
	}
	return DeltaOpNodeRemove{Node: fNode}, nil
}

// DeltaOpEdgeAdd: A dependency edge was added.
type DeltaOpEdgeAdd struct {
	// Dependent: Node that reads `dependency`.
	Dependent NodeId
	// Dependency: Node read by `dependent`.
	Dependency NodeId
}

func (DeltaOpEdgeAdd) isDeltaOp() {}

// MarshalJSON emits {"EdgeAdd": {...}}, omitting an absent optional field.
func (o DeltaOpEdgeAdd) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.EdgeAdd.dependent", o.Dependent); err != nil {
		return nil, err
	}
	if err := deltaWireCheckInt64("DeltaOp.EdgeAdd.dependency", o.Dependency); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"dependent", o.Dependent},
		{"dependency", o.Dependency},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("EdgeAdd", json.RawMessage(inner))
}

func unmarshalDeltaOpEdgeAdd(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.EdgeAdd", data, []string{"dependent", "dependency"}, nil)
	if err != nil {
		return nil, err
	}
	fDependent, err := deltaWireInt64("DeltaOp.EdgeAdd.dependent", f["dependent"])
	if err != nil {
		return nil, err
	}
	fDependency, err := deltaWireInt64("DeltaOp.EdgeAdd.dependency", f["dependency"])
	if err != nil {
		return nil, err
	}
	return DeltaOpEdgeAdd{Dependent: fDependent, Dependency: fDependency}, nil
}

// DeltaOpEdgeRemove: A dependency edge was removed.
type DeltaOpEdgeRemove struct {
	// Dependent: Node that reads `dependency`.
	Dependent NodeId
	// Dependency: Node read by `dependent`.
	Dependency NodeId
}

func (DeltaOpEdgeRemove) isDeltaOp() {}

// MarshalJSON emits {"EdgeRemove": {...}}, omitting an absent optional field.
func (o DeltaOpEdgeRemove) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.EdgeRemove.dependent", o.Dependent); err != nil {
		return nil, err
	}
	if err := deltaWireCheckInt64("DeltaOp.EdgeRemove.dependency", o.Dependency); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"dependent", o.Dependent},
		{"dependency", o.Dependency},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("EdgeRemove", json.RawMessage(inner))
}

func unmarshalDeltaOpEdgeRemove(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.EdgeRemove", data, []string{"dependent", "dependency"}, nil)
	if err != nil {
		return nil, err
	}
	fDependent, err := deltaWireInt64("DeltaOp.EdgeRemove.dependent", f["dependent"])
	if err != nil {
		return nil, err
	}
	fDependency, err := deltaWireInt64("DeltaOp.EdgeRemove.dependency", f["dependency"])
	if err != nil {
		return nil, err
	}
	return DeltaOpEdgeRemove{Dependent: fDependent, Dependency: fDependency}, nil
}

// DeltaOpQueuePush: Op-log delta form for a QueueCell node: append `payload` to
// the tail. The op-log delta is the incremental counterpart to the
// storage-snapshot form (cell-model.md § Wire and snapshot shape); a run of
// same-direction QueuePush ops fuses into one multi-epoch batch Delta
// (protocol.md § Backpressure & outbox coalescing).
type DeltaOpQueuePush struct {
	// Node: Target node.
	Node NodeId
	// Payload: Value, inline or by blob descriptor.
	Payload IpcValue
}

func (DeltaOpQueuePush) isDeltaOp() {}

// MarshalJSON emits {"QueuePush": {...}}, omitting an absent optional field.
func (o DeltaOpQueuePush) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.QueuePush.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
		{"payload", o.Payload},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("QueuePush", json.RawMessage(inner))
}

func unmarshalDeltaOpQueuePush(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.QueuePush", data, []string{"node", "payload"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.QueuePush.node", f["node"])
	if err != nil {
		return nil, err
	}
	fPayload, err := unmarshalIpcValue(f["payload"])
	if err != nil {
		return nil, err
	}
	return DeltaOpQueuePush{Node: fNode, Payload: fPayload}, nil
}

// DeltaOpQueuePop: Op-log delta form for a QueueCell node: remove the head.
// Carries no value (the popped element is determined by ordered replay); a
// re-delivered pop is Ignored by the epoch gap rule. Crosses the wire only when
// consumption is authoritatively replicated (mirror sync); in the default
// producer→consumer sync the remote consumer's pops are local. A
// QueuePop/QueueClose is a fusion boundary (order-sensitive).
type DeltaOpQueuePop struct {
	// Node: Target node.
	Node NodeId
}

func (DeltaOpQueuePop) isDeltaOp() {}

// MarshalJSON emits {"QueuePop": {...}}, omitting an absent optional field.
func (o DeltaOpQueuePop) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.QueuePop.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("QueuePop", json.RawMessage(inner))
}

func unmarshalDeltaOpQueuePop(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.QueuePop", data, []string{"node"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.QueuePop.node", f["node"])
	if err != nil {
		return nil, err
	}
	return DeltaOpQueuePop{Node: fNode}, nil
}

// DeltaOpQueueClose: Op-log delta form for a QueueCell node: mark closed
// (idempotent, terminal — Closed is distinct from Empty). A fusion boundary.
type DeltaOpQueueClose struct {
	// Node: Target node.
	Node NodeId
}

func (DeltaOpQueueClose) isDeltaOp() {}

// MarshalJSON emits {"QueueClose": {...}}, omitting an absent optional field.
func (o DeltaOpQueueClose) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("DeltaOp.QueueClose.node", o.Node); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"node", o.Node},
	}
	inner, err := deltaWireObject(fields)
	if err != nil {
		return nil, err
	}
	return deltaWireTagged("QueueClose", json.RawMessage(inner))
}

func unmarshalDeltaOpQueueClose(data json.RawMessage) (DeltaOp, error) {
	f, err := deltaWireFields("DeltaOp.QueueClose", data, []string{"node"}, nil)
	if err != nil {
		return nil, err
	}
	fNode, err := deltaWireInt64("DeltaOp.QueueClose.node", f["node"])
	if err != nil {
		return nil, err
	}
	return DeltaOpQueueClose{Node: fNode}, nil
}

// Delta: Incremental change set: ordered ops that take the receiver from
// `base_epoch` to `epoch`.
type Delta struct {
	// BaseEpoch: Epoch this delta applies to (must equal the receiver's
	// last_epoch).
	BaseEpoch Epoch
	// Epoch: New epoch, >= base_epoch + 1. Usually base_epoch + 1; a
	// multi-epoch-span delta has epoch > base_epoch + 1 (epoch - base_epoch =
	// accepted-event span). See protocol.md § Multi-epoch-span delta.
	Epoch Epoch
	// Ops: Ordered operations.
	Ops []DeltaOp
}

// MarshalJSON emits Delta, writing absent lists as [] rather than null.
func (r Delta) MarshalJSON() ([]byte, error) {
	if err := deltaWireCheckInt64("Delta.base_epoch", r.BaseEpoch); err != nil {
		return nil, err
	}
	if err := deltaWireCheckInt64("Delta.epoch", r.Epoch); err != nil {
		return nil, err
	}
	fields := []deltaWireField{
		{"base_epoch", r.BaseEpoch},
		{"epoch", r.Epoch},
		{"ops", deltaWireNonNil(r.Ops)},
	}
	return deltaWireObject(fields)
}

// UnmarshalJSON decodes Delta strictly: the declared keys only, each well-typed.
func (r *Delta) UnmarshalJSON(data []byte) error {
	f, err := deltaWireFields("Delta", data, []string{"base_epoch", "epoch", "ops"}, nil)
	if err != nil {
		return err
	}
	fBaseEpoch, err := deltaWireInt64("Delta.base_epoch", f["base_epoch"])
	if err != nil {
		return err
	}
	fEpoch, err := deltaWireInt64("Delta.epoch", f["epoch"])
	if err != nil {
		return err
	}
	fOpsItems, err := deltaWireList("Delta.ops", f["ops"])
	if err != nil {
		return err
	}
	fOps := make([]DeltaOp, len(fOpsItems))
	for i, item := range fOpsItems {
		v, err := unmarshalDeltaOp(item)
		if err != nil {
			return err
		}
		fOps[i] = v
	}
	*r = Delta{BaseEpoch: fBaseEpoch, Epoch: fEpoch, Ops: fOps}
	return nil
}

// IpcValue: Externally-tagged delta payload: inline bytes or a shared-memory
// blob reference.
type IpcValue interface {
	json.Marshaler
	isIpcValue()
}

// unmarshalIpcValue decodes a IpcValue strictly: exactly one known variant.
func unmarshalIpcValue(raw json.RawMessage) (IpcValue, error) {
	tag, inner, err := deltaWireTag("IpcValue", raw)
	if err != nil {
		return nil, err
	}
	switch tag {
	case "Inline":
		return unmarshalIpcValueInline(inner)
	case "SharedBlob":
		return unmarshalIpcValueSharedBlob(inner)
	}
	return nil, fmt.Errorf("unknown IpcValue variant: %s", tag)
}

// IpcValueInline: Inline serialized bytes as JSON array of u8 (NOT base64).
type IpcValueInline struct {
	Bytes []byte
}

func (IpcValueInline) isIpcValue() {}

// MarshalJSON emits {"Inline": ...}.
func (v IpcValueInline) MarshalJSON() ([]byte, error) {
	return deltaWireTagged("Inline", deltaWireByteArray(v.Bytes))
}

func unmarshalIpcValueInline(data json.RawMessage) (IpcValue, error) {
	value, err := deltaWireBytes("IpcValue.Inline", data)
	if err != nil {
		return nil, err
	}
	return IpcValueInline{Bytes: value}, nil
}

// IpcValueSharedBlob: Value stored in a blob backend, by descriptor.
type IpcValueSharedBlob struct {
	Blob ShmBlobRef
}

func (IpcValueSharedBlob) isIpcValue() {}

// MarshalJSON emits {"SharedBlob": ...}.
func (v IpcValueSharedBlob) MarshalJSON() ([]byte, error) {
	return deltaWireTagged("SharedBlob", v.Blob)
}

func unmarshalIpcValueSharedBlob(data json.RawMessage) (IpcValue, error) {
	var value ShmBlobRef
	if err := json.Unmarshal(data, &value); err != nil {
		return nil, fmt.Errorf("IpcValue.SharedBlob: %w", err)
	}
	return IpcValueSharedBlob{Blob: value}, nil
}

// NodeState: Externally-tagged node body: concrete bytes, a shared-memory
// value, or an opaque (visible but non-serializable) node.
type NodeState interface {
	json.Marshaler
	isNodeState()
}

// unmarshalNodeState decodes a NodeState strictly: exactly one known variant.
func unmarshalNodeState(raw json.RawMessage) (NodeState, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) > 0 && trimmed[0] == '"' {
		var s string
		if err := json.Unmarshal(trimmed, &s); err != nil {
			return nil, err
		}
		switch s {
		case "Opaque":
			return NodeStateOpaque{}, nil
		}
		return nil, fmt.Errorf("unknown NodeState unit variant: %s", s)
	}
	tag, inner, err := deltaWireTag("NodeState", raw)
	if err != nil {
		return nil, err
	}
	switch tag {
	case "Payload":
		return unmarshalNodeStatePayload(inner)
	case "SharedBlob":
		return unmarshalNodeStateSharedBlob(inner)
	}
	return nil, fmt.Errorf("unknown NodeState variant: %s", tag)
}

// NodeStatePayload: Serialized value bytes as JSON array of u8 (NOT base64).
type NodeStatePayload struct {
	Bytes []byte
}

func (NodeStatePayload) isNodeState() {}

// MarshalJSON emits {"Payload": ...}.
func (v NodeStatePayload) MarshalJSON() ([]byte, error) {
	return deltaWireTagged("Payload", deltaWireByteArray(v.Bytes))
}

func unmarshalNodeStatePayload(data json.RawMessage) (NodeState, error) {
	value, err := deltaWireBytes("NodeState.Payload", data)
	if err != nil {
		return nil, err
	}
	return NodeStatePayload{Bytes: value}, nil
}

// NodeStateSharedBlob: Value stored in a blob backend, by descriptor.
type NodeStateSharedBlob struct {
	Blob ShmBlobRef
}

func (NodeStateSharedBlob) isNodeState() {}

// MarshalJSON emits {"SharedBlob": ...}.
func (v NodeStateSharedBlob) MarshalJSON() ([]byte, error) {
	return deltaWireTagged("SharedBlob", v.Blob)
}

func unmarshalNodeStateSharedBlob(data json.RawMessage) (NodeState, error) {
	var value ShmBlobRef
	if err := json.Unmarshal(data, &value); err != nil {
		return nil, fmt.Errorf("NodeState.SharedBlob: %w", err)
	}
	return NodeStateSharedBlob{Blob: value}, nil
}

// NodeStateOpaque: Visible but non-serializable node: no body crosses the wire.
type NodeStateOpaque struct{}

func (NodeStateOpaque) isNodeState() {}

// MarshalJSON emits the bare unit tag "Opaque".
func (NodeStateOpaque) MarshalJSON() ([]byte, error) { return json.Marshal("Opaque") }

// deltaWireNonNil returns s, or an empty slice when s is nil, so it encodes as [].
func deltaWireNonNil[T any](s []T) []T {
	if s == nil {
		return []T{}
	}
	return s
}
