// Code generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.
// Surface `receipts` from schemas/receipts.json, model sha256:faf31f5c1db054295114b513d51ae6d4b7b47658147cf8044838340a72946b87.
// Regenerate from lazily-spec with `make wire-codegen`; semantics stay hand-written.
// Externally-tagged envelopes are not lowered for Go; callers decode the tagged body.

package lazily

import (
	"encoding/json"
	"fmt"
)

// ReceiptOutcome: Outcome vocabulary. observed/accepted are non-terminal;
// applied/rejected are terminal.
type ReceiptOutcome string

const (
	// ReceiptOutcomeObserved: A peer/process observed the causation request.
	ReceiptOutcomeObserved ReceiptOutcome = "observed"
	// ReceiptOutcomeAccepted: A peer/process accepted or queued the request.
	ReceiptOutcomeAccepted ReceiptOutcome = "accepted"
	// ReceiptOutcomeApplied: The requested effect/state change was applied.
	ReceiptOutcomeApplied ReceiptOutcome = "applied"
	// ReceiptOutcomeRejected: The requested effect/state change was rejected.
	ReceiptOutcomeRejected ReceiptOutcome = "rejected"
)

// Wire returns the bare wire string of this ReceiptOutcome.
func (v ReceiptOutcome) Wire() string { return string(v) }

// ReceiptOutcomeFromWire parses a wire string into a ReceiptOutcome, rejecting unknown
// values.
func ReceiptOutcomeFromWire(v string) (ReceiptOutcome, error) {
	switch ReceiptOutcome(v) {
	case ReceiptOutcomeObserved, ReceiptOutcomeAccepted, ReceiptOutcomeApplied, ReceiptOutcomeRejected:
		return ReceiptOutcome(v), nil
	default:
		return "", fmt.Errorf("unknown ReceiptOutcome: %q", v)
	}
}

// UnmarshalJSON decodes a ReceiptOutcome wire string, rejecting unknown values.
func (v *ReceiptOutcome) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := ReceiptOutcomeFromWire(s)
	if err != nil {
		return err
	}
	*v = parsed
	return nil
}

// CausalReceipt: One receipt event for a command/effect causation id.
type CausalReceipt struct {
	// ReceiptId: Idempotency key for this receipt event.
	ReceiptId string `json:"receipt_id"`
	// CausationId: Stable id of the command, event, or effect request this receipt
	// observes.
	CausationId string `json:"causation_id"`
	// Observer: Peer, process, or subsystem that produced the receipt.
	Observer string `json:"observer"`
	// Generation: Producer/editor generation. Consumers discard receipts outside
	// the current generation for the causation id.
	Generation uint64 `json:"generation"`
	// Outcome: Receipt outcome.
	Outcome ReceiptOutcome `json:"outcome"`
	// Reason: Optional human/debug rejection reason.
	Reason *string `json:"reason"`
	// PayloadHash: Optional hash of the state/payload observed by the receipt.
	PayloadHash *string `json:"payload_hash"`
}

// CausalReceiptFromWire decodes a CausalReceipt from its JSON wire form.
func CausalReceiptFromWire(data []byte) (CausalReceipt, error) {
	var r CausalReceipt
	if err := json.Unmarshal(data, &r); err != nil {
		return CausalReceipt{}, err
	}
	return r, nil
}

// CausalReceipts: Wire body for the externally-tagged `CausalReceipts`
// envelope.
type CausalReceipts struct {
	// Receipts: Receipt batch.
	Receipts []CausalReceipt `json:"receipts"`
}

// MarshalJSON emits CausalReceipts, writing absent lists as [] rather than null.
func (r CausalReceipts) MarshalJSON() ([]byte, error) {
	type wire CausalReceipts
	w := wire(r)
	if w.Receipts == nil {
		w.Receipts = []CausalReceipt{}
	}
	return json.Marshal(w)
}

// CausalReceiptsFromWire decodes a CausalReceipts from its JSON wire form.
func CausalReceiptsFromWire(data []byte) (CausalReceipts, error) {
	var r CausalReceipts
	if err := json.Unmarshal(data, &r); err != nil {
		return CausalReceipts{}, err
	}
	return r, nil
}
